DROP USER
IF EXISTS 'admin_001'@'%';

CREATE USER
IF NOT EXISTS 'admin_001'@'%';

CREATE USER rt IDENTIFIED BY '123';
 FAILED_LOGIN_ATTEMPTS 0
 PASSWORD_LOCK_TIME 0
 PASSWORD EXPIRE INTERVAL 90 DAY
 PASSWORD REUSE INTERVAL 365 DAY;

CREATE USER brt IDENTIFIED BY '321';
 FAILED_LOGIN_ATTEMPTS 0
 PASSWORD_LOCK_TIME 0
 PASSWORD EXPIRE INTERVAL 90 DAY
 PASSWORD HISTORY 5
 PASSWORD REUSE INTERVAL 365 DAY;

CREATE USER admin_007 IDENTIFIED BY '213';
 PASSWORD_LOCK_TIME UNBOUNDED
 PASSWORD EXPIRE INTERVAL 90 DAY
 PASSWORD HISTORY 5
 PASSWORD REUSE INTERVAL 365 DAY;
